name: Release

on:
  push:
    tags:
      - "v*"

jobs:
  release:
    name: Create HACS release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: "16"

      - name: Build
        run: |
          npm install
          npx rollup -c -m

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: dist/spotify-card-v2.js
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
